### PR TITLE
Add "--sysimage" flag

### PR DESCRIPTION
**Pull request by lucatrv**

### CODE REVIEW

**Comment by ViralBShah** [comment]
Do you think we can enable CI for this repo?

**Comment by lucatrv** [comment]
Fine for me, but I would not know how to do it, apart from following a tutorial such as these:
[https://docs.travis-ci.com/user/getting-started/](https://docs.travis-ci.com/user/getting-started/)
[https://docs.travis-ci.com/user/languages/julia/](https://docs.travis-ci.com/user/languages/julia/)

BTW, this PR is the last one that I planned for version 0.6. With next commits, I was planning to transition to version 0.7 (which would require Julia 0.7). Because of this, after merging this PR, I would suggest to create a new branch named `release-0.6` which would keep compatibility with Julia 0.6 (although I do not plan to commit to it anymore).

With next commits, I would also implement the proper changes to make functions in `julia-config.jl` and `build_sysimg.jl` easily accessible by `juliac.jl`. I opened a [discussion](https://discourse.julialang.org/t/proposal-to-make-functions-in-julia-config-jl-and-build-sysimg-jl-reusable/8578) to ask for suggestions, I will wait for answers and decision before proceeding.

**Comment by lucatrv** [comment]
@ViralBShah please disregard what I wrote about Julia v0.6 / v07, as I decided to add support for new Julia v0.7 functionalities while keeping compatibility for v0.6 (for the time being). So you do not need to create a new branch named `release-0.6`.

Please notice however that I am still waiting for directions on how to access functions in `julia-config.jl` and `build_sysimg.jl` programmatically (see [discussion](https://discourse.julialang.org/t/proposal-to-make-functions-in-julia-config-jl-and-build-sysimg-jl-reusable/8578)).

Thanks

**Comment by ViralBShah** [comment]
Didn't we have an open issue/PR in the Julia repo for this?

**Comment by lucatrv** [comment]
Yes, time ago I created [PR #24427](https://github.com/JuliaLang/julia/pull/24427) on the Julia repo, however it is still open. At the time I used the names `JuliaConfig.jl` and `julia-config.jl`, then I proposed using `BuildTools.jl` and `build_config.jl`, but I did not get a confirmation. There was also discussion to move everything to `stdlib`.
I opened this [discussion](https://discourse.julialang.org/t/proposal-to-make-functions-in-julia-config-jl-and-build-sysimg-jl-reusable/8578) to finally get a clear understanding of what exactly should be done, then I could work on a new PR.

**Pull request merged**
