### PR TITLE
Use different directories for script, program, and compilation

### PR DESCRIPTION
**Pull request by lucatrv**

### CODE REVIEW

**Comment by lucatrv** [comment]
Notice that also file 'README.md' should be updated at point 'For now, make sure that the driver program is also in the static-julia directory'.

**Comment by ViralBShah** [comment]
Could you also provide a README update in this PR as suggested? Thanks. Is the plan to make the driver independent of the static-julia directory as well?

**Comment by lucatrv** [comment]
I have just updated 'README.md'.
IMHO the standard 'program.c' could be kept in the 'static-julia' directory, as it should be used as it is in most cases. I would implement optional parameters to output either the '.o' or the '.so' files only, and to change the compilation directory (the default is 'builddir', same used by 'Meson'). So for complex programs that need to link with different 'c' programs, one would run first 'juliac' and then the compiler with proper options using a build system. What do you think?

**Comment by ViralBShah** [comment]
Yes, good idea to have separate flags to get the `.o` and `.so` files.

I guess if the usage model is that you clone `static-julia` into your own project as a subdirectory, then having the driver in there makes sense. If we want it to be part of the standard julia distribution, then we can't have any project specific files inside.

**Comment by ViralBShah** [comment]
Let me know if you would like me to merge this, and do the .o and .so generation flags in a separate PR.

**Pull request merged**
