### PR TITLE
Auto detect Julia paths

### PR DESCRIPTION
**Pull request by lucatrv**

### CODE REVIEW

**Comment by ViralBShah** [comment]
While we don't have CI on this repo - have you tried this out on at least mac/linux and windows? Looks ok.

**Comment by lucatrv** [comment]
I am always testing my PRs on both Linux and Windows. I have others to submit, fixing issues #1 and #2 and adding new features.

**Comment by ViralBShah** [comment]
Thank you. This is really making the script much easier to use!

**Comment by mauro3** [comment]
This needs a README update too.

**Comment by lucatrv** [comment]
Done in next PR

**Pull request merged**
