### PR TITLE
Choose builddir and output files

### PR DESCRIPTION
**Pull request by lucatrv**

### CODE REVIEW

**Comment by ViralBShah** [comment]
Should we make this a package and register it, if we need dependencies? It is a bit weird though to have to `Pkg.add()` to get a `juliac.jl` script.

**Comment by lucatrv** [comment]
I would think so. Hopefully in future the Julia main install will include some fundamental packages, such as StaticJulia and ArgParse (Python for example includes [argparse](https://docs.python.org/3/library/argparse.html)).

**Comment by ViralBShah** [comment]
@lucatrv I am thinking out aloud. Perhaps if we were to package this as a Julia package, then perhaps the code can be refactored so that we can trigger the compilation from within a Julia session itself. `juliac.jl` can simply then be a wrapper script around this programmatic way to compile the package, while `StaticJulia.jl` can be a package itself. 

Does that make sense?

**Comment by lucatrv** [comment]
I think the main `julia_compile` function could be included in Julia, while the rest of the `juliac.jl` script could go in package `StaticJulia.jl`, which would depend on `ArgParse`. Of course we would simplify the `hello.jl` example so as not add other dependencies (currently `Distributions` and `UnicodePlots`).
FYI I am now working on Julia v0.7 support, and adding options `--o-name` `--s-name` `--e-name` to customize object file / shared library / executable names.
One question: is the `program.jl` file still useful or is it now superseded by `hello.jl`?

**Comment by ViralBShah** [comment]
Deleted a few files. Maybe move the rest of this discussion to a new issue? I'll try out the 0.7 stuff.

**Comment by lucatrv** [comment]
Ok, thanks, I am going to open a new issue once I have submitted the PR for preliminary Julia v0.7 support

**Pull request merged**
